import React from 'react';
import Header from './Components/Header/Header';
import SearchBar from './Components/SearchBar/SearchBar';
import BookGrid from './Components/BookGrid/BookGrid'; 
import './App.css';

const App = () => {
    const books = [
{ id: 1, title: 'Book One', cover: 'link_to_cover_image_1' },
{ id: 2, title: 'Book Two', cover: 'link_to_cover_image_2' },
{ id: 3, title: 'Book Three', cover: 'link_to_cover_image_3' },
{ id: 4, title: 'Book Four', cover: 'link_to_cover_image_4' },
{ id: 5, title: 'Book Five', cover: 'link_to_cover_image_5' },
{ id: 6, title: 'Book Six', cover: 'link_to_cover_image_6' },
{ id: 7, title: 'Book Seven', cover: 'link_to_cover_image_7' },
{ id: 8, title: 'Book Eight', cover: 'link_to_cover_image_8' },
{ id: 9, title: 'Book Nine', cover: 'link_to_cover_image_9' },
{ id: 10, title: 'Book Ten', cover: 'link_to_cover_image_10' },
{ id: 11, title: 'Book Eleven', cover: 'link_to_cover_image_11' },
{ id: 12, title: 'Book Twelve', cover: 'link_to_cover_image_12' },
{ id: 13, title: 'Book Thirteen', cover: 'link_to_cover_image_13' },
{ id: 14, title: 'Book Fourteen', cover: 'link_to_cover_image_14' },
{ id: 15, title: 'Book Fifteen', cover: 'link_to_cover_image_15' },
{ id: 16, title: 'Book Sixteen', cover: 'link_to_cover_image_16' },
{ id: 17, title: 'Book Seventeen', cover: 'link_to_cover_image_17' },
{ id: 18, title: 'Book Eighteen', cover: 'link_to_cover_image_18' },
{ id: 19, title: 'Book Nineteen', cover: 'link_to_cover_image_19' },
{ id: 20, title: 'Book Twenty', cover: 'link_to_cover_image_20' },
{ id: 21, title: 'Book Twenty-One', cover: 'link_to_cover_image_21' },
{ id: 22, title: 'Book Twenty-Two', cover: 'link_to_cover_image_22' },
{ id: 23, title: 'Book Twenty-Three', cover: 'link_to_cover_image_23' },
{ id: 24, title: 'Book Twenty-Four', cover: 'link_to_cover_image_24' },
{ id: 25, title: 'Book Twenty-Five', cover: 'link_to_cover_image_25' },
{ id: 26, title: 'Book Twenty-Six', cover: 'link_to_cover_image_26' },
{ id: 27, title: 'Book Twenty-Seven', cover: 'link_to_cover_image_27' },
{ id: 28, title: 'Book Twenty-Eight', cover: 'link_to_cover_image_28' },
{ id: 29, title: 'Book Twenty-Nine', cover: 'link_to_cover_image_29' },
{ id: 30, title: 'Book Thirty', cover: 'link_to_cover_image_30' },
{ id: 31, title: 'Book Thirty-One', cover: 'link_to_cover_image_31' },
{ id: 32, title: 'Book Thirty-Two', cover: 'link_to_cover_image_32' },
{ id: 33, title: 'Book Thirty-Three', cover: 'link_to_cover_image_33' },
{ id: 34, title: 'Book Thirty-Four', cover: 'link_to_cover_image_34' },
{ id: 35, title: 'Book Thirty-Five', cover: 'link_to_cover_image_35' },
{ id: 36, title: 'Book Thirty-Six', cover: 'link_to_cover_image_36' },
{ id: 37, title: 'Book Thirty-Seven', cover: 'link_to_cover_image_37' },
{ id: 38, title: 'Book Thirty-Eight', cover: 'link_to_cover_image_38' },
{ id: 39, title: 'Book Thirty-Nine', cover: 'link_to_cover_image_39' },
{ id: 40, title: 'Book Forty', cover: 'link_to_cover_image_40' },
{ id: 41, title: 'Book Forty-One', cover: 'link_to_cover_image_41' },
{ id: 42, title: 'Book Forty-Two', cover: 'link_to_cover_image_42' },
{ id: 43, title: 'Book Forty-Three', cover: 'link_to_cover_image_43' },
{ id: 44, title: 'Book Forty-Four', cover: 'link_to_cover_image_44' },
{ id: 45, title: 'Book Forty-Five', cover: 'link_to_cover_image_45' },
{ id: 46, title: 'Book Forty-Six', cover: 'link_to_cover_image_46' },
{ id: 47, title: 'Book Forty-Seven', cover: 'link_to_cover_image_47' },
{ id: 48, title: 'Book Forty-Eight', cover: 'link_to_cover_image_48' },
{ id: 49, title: 'Book Forty-Nine', cover: 'link_to_cover_image_49' },
{ id: 50, title: 'Book Fifty', cover: 'link_to_cover_image_50' },
{ id: 51, title: 'Book Fifty-One', cover: 'link_to_cover_image_51' },
{ id: 52, title: 'Book Fifty-Two', cover: 'link_to_cover_image_52' },
{ id: 53, title: 'Book Fifty-Three', cover: 'link_to_cover_image_53' },
{ id: 54, title: 'Book Fifty-Four', cover: 'link_to_cover_image_54' },
{ id: 55, title: 'Book Fifty-Five', cover: 'link_to_cover_image_55' },
{ id: 56, title: 'Book Fifty-Six', cover: 'link_to_cover_image_56' },
{ id: 57, title: 'Book Fifty-Seven', cover: 'link_to_cover_image_57' },
{ id: 58, title: 'Book Fifty-Eight', cover: 'link_to_cover_image_58' },
{ id: 59, title: 'Book Fifty-Nine', cover: 'link_to_cover_image_59' },
{ id: 60, title: 'Book Sixty', cover: 'link_to_cover_image_60' },
{ id: 61, title: 'Book Sixty-One', cover: 'link_to_cover_image_61' },
{ id: 62, title: 'Book Sixty-Two', cover: 'link_to_cover_image_62' },
{ id: 63, title: 'Book Sixty-Three', cover: 'link_to_cover_image_63' },
{ id: 64, title: 'Book Sixty-Four', cover: 'link_to_cover_image_64' },
{ id: 65, title: 'Book Sixty-Five', cover: 'link_to_cover_image_65' },
{ id: 66, title: 'Book Sixty-Six', cover: 'link_to_cover_image_66' },
{ id: 67, title: 'Book Sixty-Seven', cover: 'link_to_cover_image_67' },
{ id: 68, title: 'Book Sixty-Eight', cover: 'link_to_cover_image_68' },
{ id: 69, title: 'Book Sixty-Nine', cover: 'link_to_cover_image_69' },
{ id: 70, title: 'Book Seventy', cover: 'link_to_cover_image_70' },
{ id: 71, title: 'Book Seventy-One', cover: 'link_to_cover_image_71' },
{ id: 72, title: 'Book Seventy-Two', cover: 'link_to_cover_image_72' },
{ id: 73, title: 'Book Seventy-Three', cover: 'link_to_cover_image_73' },
{ id: 74, title: 'Book Seventy-Four', cover: 'link_to_cover_image_74' },
{ id: 75, title: 'Book Seventy-Five', cover: 'link_to_cover_image_75' },
{ id: 76, title: 'Book Seventy-Six', cover: 'link_to_cover_image_76' },
{ id: 77, title: 'Book Seventy-Seven', cover: 'link_to_cover_image_77' },
{ id: 78, title: 'Book Seventy-Eight', cover: 'link_to_cover_image_78' },
{ id: 79, title: 'Book Seventy-Nine', cover: 'link_to_cover_image_79' },
{ id: 80, title: 'Book Eighty', cover: 'link_to_cover_image_80' },
{ id: 81, title: 'Book Eighty-One', cover: 'link_to_cover_image_81' },
{ id: 82, title: 'Book Eighty-Two', cover: 'link_to_cover_image_82' },
{ id: 83, title: 'Book Eighty-Three', cover: 'link_to_cover_image_83' },
{ id: 84, title: 'Book Eighty-Four', cover: 'link_to_cover_image_84' },
{ id: 85, title: 'Book Eighty-Five', cover: 'link_to_cover_image_85' },
{ id: 86, title: 'Book Eighty-Six', cover: 'link_to_cover_image_86' },
{ id: 87, title: 'Book Eighty-Seven', cover: 'link_to_cover_image_87' },
{ id: 88, title: 'Book Eighty-Eight', cover: 'link_to_cover_image_88' },
{ id: 89, title: 'Book Eighty-Nine', cover: 'link_to_cover_image_89' },
{ id: 90, title: 'Book Ninety', cover: 'link_to_cover_image_90' },
{ id: 91, title: 'Book Ninety-One', cover: 'link_to_cover_image_91' },
{ id: 92, title: 'Book Ninety-Two', cover: 'link_to_cover_image_92' },
{ id: 93, title: 'Book Ninety-Three', cover: 'link_to_cover_image_93' },
{ id: 94, title: 'Book Ninety-Four', cover: 'link_to_cover_image_94' },
{ id: 95, title: 'Book Ninety-Five', cover: 'link_to_cover_image_95' },
{ id: 96, title: 'Book Ninety-Six', cover: 'link_to_cover_image_96' },
{ id: 97, title: 'Book Ninety-Seven', cover: 'link_to_cover_image_97' },
{ id: 98, title: 'Book Ninety-Eight', cover: 'link_to_cover_image_98' },
{ id: 99, title: 'Book Ninety-Nine', cover: 'link_to_cover_image_99' },
{ id: 100, title: 'Book One Hundred', cover: 'link_to_cover_image_100' },
{ id: 101, title: 'Book One Hundred One', cover: 'link_to_cover_image_101' },
{ id: 102, title: 'Book One Hundred Two', cover: 'link_to_cover_image_102' },
{ id: 103, title: 'Book One Hundred Three', cover: 'link_to_cover_image_103' },
{ id: 104, title: 'Book One Hundred Four', cover: 'link_to_cover_image_104' },
{ id: 105, title: 'Book One Hundred Five', cover: 'link_to_cover_image_105' },
{ id: 106, title: 'Book One Hundred Six', cover: 'link_to_cover_image_106' },
{ id: 107, title: 'Book One Hundred Seven', cover: 'link_to_cover_image_107' },
{ id: 108, title: 'Book One Hundred Eight', cover: 'link_to_cover_image_108' },
{ id: 109, title: 'Book One Hundred Nine', cover: 'link_to_cover_image_109' },
{ id: 110, title: 'Book One Hundred Ten', cover: 'link_to_cover_image_110' },
{ id: 111, title: 'Book One Hundred Eleven', cover: 'link_to_cover_image_111' },
{ id: 112, title: 'Book One Hundred Twelve', cover: 'link_to_cover_image_112' },
{ id: 113, title: 'Book One Hundred Thirteen', cover: 'link_to_cover_image_113' },
{ id: 114, title: 'Book One Hundred Fourteen', cover: 'link_to_cover_image_114' },
{ id: 115, title: 'Book One Hundred Fifteen', cover: 'link_to_cover_image_115' },
{ id: 116, title: 'Book One Hundred Sixteen', cover: 'link_to_cover_image_116' },
{ id: 117, title: 'Book One Hundred Seventeen', cover: 'link_to_cover_image_117' },
{ id: 118, title: 'Book One Hundred Eighteen', cover: 'link_to_cover_image_118' },
{ id: 119, title: 'Book One Hundred Nineteen', cover: 'link_to_cover_image_119' },
{ id: 120, title: 'Book One Hundred Twenty', cover: 'link_to_cover_image_120' },
{ id: 121, title: 'Book One Hundred Twenty-One', cover: 'link_to_cover_image_121' },
{ id: 122, title: 'Book One Hundred Twenty-Two', cover: 'link_to_cover_image_122' },
{ id: 123, title: 'Book One Hundred Twenty-Three', cover: 'link_to_cover_image_123' },
{ id: 124, title: 'Book One Hundred Twenty-Four', cover: 'link_to_cover_image_124' },
{ id: 125, title: 'Book One Hundred Twenty-Five', cover: 'link_to_cover_image_125' },
{ id: 126, title: 'Book One Hundred Twenty-Six', cover: 'link_to_cover_image_126' },
{ id: 127, title: 'Book One Hundred Twenty-Seven', cover: 'link_to_cover_image_127' },
{ id: 128, title: 'Book One Hundred Twenty-Eight', cover: 'link_to_cover_image_128' },
{ id: 129, title: 'Book One Hundred Twenty-Nine', cover: 'link_to_cover_image_129' },
{ id: 130, title: 'Book One Hundred Thirty', cover: 'link_to_cover_image_130' },
{ id: 131, title: 'Book One Hundred Thirty-One', cover: 'link_to_cover_image_131' },
{ id: 132, title: 'Book One Hundred Thirty-Two', cover: 'link_to_cover_image_132' },
{ id: 133, title: 'Book One Hundred Thirty-Three', cover: 'link_to_cover_image_133' },
{ id: 134, title: 'Book One Hundred Thirty-Four', cover: 'link_to_cover_image_134' },
{ id: 135, title: 'Book One Hundred Thirty-Five', cover: 'link_to_cover_image_135' },
{ id: 136, title: 'Book One Hundred Thirty-Six', cover: 'link_to_cover_image_136' },
{ id: 137, title: 'Book One Hundred Thirty-Seven', cover: 'link_to_cover_image_137' },
{ id: 138, title: 'Book One Hundred Thirty-Eight', cover: 'link_to_cover_image_138' },
{ id: 139, title: 'Book One Hundred Thirty-Nine', cover: 'link_to_cover_image_139' },
{ id: 140, title: 'Book One Hundred Forty', cover: 'link_to_cover_image_140' },
{ id: 141, title: 'Book One Hundred Forty-One', cover: 'link_to_cover_image_141' },
{ id: 142, title: 'Book One Hundred Forty-Two', cover: 'link_to_cover_image_142' },
{ id: 143, title: 'Book One Hundred Forty-Three', cover: 'link_to_cover_image_143' },
{ id: 144, title: 'Book One Hundred Forty-Four', cover: 'link_to_cover_image_144' },
{ id: 145, title: 'Book One Hundred Forty-Five', cover: 'link_to_cover_image_145' },
{ id: 146, title: 'Book One Hundred Forty-Six', cover: 'link_to_cover_image_146' },
{ id: 147, title: 'Book One Hundred Forty-Seven', cover: 'link_to_cover_image_147' },
{ id: 148, title: 'Book One Hundred Forty-Eight', cover: 'link_to_cover_image_148' },
{ id: 149, title: 'Book One Hundred Forty-Nine', cover: 'link_to_cover_image_149' },
{ id: 150, title: 'Book One Hundred Fifty', cover: 'link_to_cover_image_150' },
{ id: 151, title: 'Book One Hundred Fifty-One', cover: 'link_to_cover_image_151' },
{ id: 152, title: 'Book One Hundred Fifty-Two', cover: 'link_to_cover_image_152' },
{ id: 153, title: 'Book One Hundred Fifty-Three', cover: 'link_to_cover_image_153' },
{ id: 154, title: 'Book One Hundred Fifty-Four', cover: 'link_to_cover_image_154' },
{ id: 155, title: 'Book One Hundred Fifty-Five', cover: 'link_to_cover_image_155' },
{ id: 156, title: 'Book One Hundred Fifty-Six', cover: 'link_to_cover_image_156' },
{ id: 157, title: 'Book One Hundred Fifty-Seven', cover: 'link_to_cover_image_157' },
{ id: 158, title: 'Book One Hundred Fifty-Eight', cover: 'link_to_cover_image_158' },
{ id: 159, title: 'Book One Hundred Fifty-Nine', cover: 'link_to_cover_image_159' },
{ id: 160, title: 'Book One Hundred Sixty', cover: 'link_to_cover_image_160' },
    ];

    return (
        <div className="app">
            <Header />
            <SearchBar />
            <BookGrid books={books} /> {}
        </div>
    );
};

export default App;
